spring:
  application:
    name: SpringService

server:
  address: 0.0.0.0
  port: 9091
  error:
    include-exception: true
    include-message: always

config:
  default-hello: "Hello There Client!"